# Generated by Django 5.1.7 on 2025-03-09 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0002_blogpost_canonical_url_blogpost_content_format_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIBlogRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(help_text='The prompt for the AI to generate a blog post')),
                ('topic', models.CharField(help_text='The main topic of the blog post', max_length=200)),
                ('keywords', models.TextField(blank=True, help_text='Keywords for SEO, comma separated')),
                ('allow_web_search', models.BooleanField(default=False, help_text='Whether the AI is allowed to search the web')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if generation failed', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_blog_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIBlogGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(blank=True)),
                ('meta_title', models.CharField(blank=True, max_length=100)),
                ('meta_description', models.TextField(blank=True)),
                ('focus_keywords', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog_post', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_generation', to='blog.blogpost')),
                ('suggested_categories', models.ManyToManyField(blank=True, related_name='ai_suggested_posts', to='blog.category')),
                ('suggested_tags', models.ManyToManyField(blank=True, related_name='ai_suggested_posts', to='blog.tag')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generation', to='ai_blog_generator.aiblogrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
