# Generated by Django 5.1 on 2025-03-11 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_blog_generator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIBlogBatchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(help_text='The main topic for this series of blog posts', max_length=200)),
                ('description', models.TextField(help_text='Description of what the series should cover')),
                ('prompt', models.TextField(help_text='Common instructions for all generated posts')),
                ('keywords', models.TextField(blank=True, help_text='Common keywords for SEO, comma separated')),
                ('num_posts', models.IntegerField(default=5, help_text='Number of blog posts to generate')),
                ('allow_web_search', models.BooleanField(default=False, help_text='Whether the AI is allowed to search the web')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('generated_ideas', models.TextField(blank=True, help_text='JSON list of generated blog post ideas', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if generation failed', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_blog_batch_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='aiblogrequest',
            name='parent_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_requests', to='ai_blog_generator.aiblogbatchrequest'),
        ),
    ]
